// Generates src/persona/active.ts based on the env PERSONA_PACK (path to a pack folder of *.ts).
// PERSONA_PACK set and exists → copy *.ts into src/persona/_pack/ and active.ts → import "./_pack".
// Otherwise → active.ts → import "./default" (neutral, personaless engine).
// The engine does NOT know the name of a specific pack: a pack is wired in ONLY via this env variable.
// active.ts and _pack/ are generated, in .gitignore. Run from prepare/pretest/precheck/predev.
import { existsSync, mkdirSync, readdirSync, copyFileSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";

const PERSONA_DIR = join(process.cwd(), "src", "persona");
const ACTIVE = join(PERSONA_DIR, "active.ts");
const STAGE = join(PERSONA_DIR, "_pack");
const HEAD = "// GENERATED by scripts/select-persona.mjs — do not edit (see env PERSONA_PACK)\n";

const pack = process.env.PERSONA_PACK;
if (pack && existsSync(pack)) {
  rmSync(STAGE, { recursive: true, force: true });
  mkdirSync(STAGE, { recursive: true });
  let n = 0;
  for (const f of readdirSync(pack)) {
    if (f.endsWith(".ts")) { copyFileSync(join(pack, f), join(STAGE, f)); n++; }
  }
  writeFileSync(ACTIVE, HEAD + 'import "./_pack";\n');
  console.log(`persona: staged ${n} file(s) from ${pack} -> src/persona/_pack`);
} else {
  rmSync(STAGE, { recursive: true, force: true });
  writeFileSync(ACTIVE, HEAD + 'import "./default";\n');
  console.log("persona: none -> neutral default" + (pack ? ` (PERSONA_PACK="${pack}" not found)` : ""));
}
