// Generates src/persona/active.ts based on the env PERSONA_PACK (path to a pack folder of *.ts).
// PERSONA_PACK set and exists → copy *.ts into src/persona/_pack/ and active.ts → import "./_pack".
// Otherwise → active.ts → import "./default" (neutral, personaless engine).
// The engine does NOT know the name of a specific pack: a pack is wired in ONLY via this env variable.
// active.ts and _pack/ are generated, in .gitignore. Run from prepare/pretest/precheck/predev.
import { existsSync, mkdirSync, readdirSync, copyFileSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";

const PERSONA_DIR = join(process.cwd(), "src", "persona");
const ACTIVE = join(PERSONA_DIR, "active.ts");
const STAGE = join(PERSONA_DIR, "_pack");
const HEAD = "// GENERATED by scripts/select-persona.mjs — do not edit (see env PERSONA_PACK)\n";

// The engine's test folder. A pack ships its own tests under <pack>/tests/*.persona.test.mjs; we stage
// them here so the gate runs them against THIS pack. They're gitignored (the `*.persona.test.mjs` glob)
// and re-cleared on every run, so neutral/another pack never inherits a stale leftover.
const TESTS_DIR = join(process.cwd(), ".claude", "skills", "testing-worker");
function clearStagedTests() {
  if (!existsSync(TESTS_DIR)) return;
  for (const f of readdirSync(TESTS_DIR)) {
    if (f.endsWith(".persona.test.mjs")) rmSync(join(TESTS_DIR, f), { force: true });
  }
}

const pack = process.env.PERSONA_PACK;
if (pack && existsSync(pack)) {
  rmSync(STAGE, { recursive: true, force: true });
  mkdirSync(STAGE, { recursive: true });
  let n = 0;
  for (const f of readdirSync(pack)) {
    if (f.endsWith(".ts")) { copyFileSync(join(pack, f), join(STAGE, f)); n++; }
  }
  // Stage the pack's i18n/ folder (its localized strings) → _pack/i18n/, so the manifest below picks it up.
  const packI18n = join(pack, "i18n");
  if (existsSync(packI18n)) {
    mkdirSync(join(STAGE, "i18n"), { recursive: true });
    for (const f of readdirSync(packI18n)) {
      if (f.endsWith(".json")) copyFileSync(join(packI18n, f), join(STAGE, "i18n", f));
    }
  }
  writeFileSync(ACTIVE, HEAD + 'import "./_pack";\n');
  // Stage the pack's tests (<pack>/tests/*.persona.test.mjs) so `npm test` exercises them against this pack.
  clearStagedTests();
  let tn = 0;
  const packTests = join(pack, "tests");
  if (existsSync(packTests) && existsSync(TESTS_DIR)) {
    for (const f of readdirSync(packTests)) {
      if (f.endsWith(".persona.test.mjs")) { copyFileSync(join(packTests, f), join(TESTS_DIR, f)); tn++; }
    }
  }
  console.log(`persona: staged ${n} file(s) from ${pack} -> src/persona/_pack` + (tn ? ` (+${tn} test file(s))` : ""));
} else {
  rmSync(STAGE, { recursive: true, force: true });
  clearStagedTests(); // neutral: drop any pack tests a previous pack build staged
  writeFileSync(ACTIVE, HEAD + 'import "./default";\n');
  console.log("persona: none -> neutral default" + (pack ? ` (PERSONA_PACK="${pack}" not found)` : ""));
}

// --- i18n manifest: discover locales from the folders (Workers have no runtime fs, so we generate
// static imports). Engine locales = src/i18n/*.json; persona locales = src/persona/_pack/i18n/*.json
// (if a pack is staged). The filename minus .json is the locale code. The code never hardcodes a
// language list — add a JSON file and it becomes available. _generated.ts is gitignored. ---
const I18N_DIR = join(process.cwd(), "src", "i18n");
const PACK_I18N = join(STAGE, "i18n");
const GEN = join(I18N_DIR, "_generated.ts");

function manifest(dir, rel, prefix) {
  if (!existsSync(dir)) return { imports: [], map: [], codes: [] };
  const files = readdirSync(dir).filter(f => f.endsWith(".json")).sort();
  const imports = [], map = [], codes = [];
  for (const f of files) {
    const code = f.replace(/\.json$/, "");
    const id = prefix + code.replace(/[^a-zA-Z0-9_]/g, "_");
    imports.push(`import ${id} from "${rel}/${f}";`);
    map.push(`  ${JSON.stringify(code)}: ${id},`);
    codes.push(code);
  }
  return { imports, map, codes };
}

const eng = manifest(I18N_DIR, ".", "_e_");
const per = manifest(PACK_I18N, "../persona/_pack/i18n", "_p_");
writeFileSync(GEN, [
  "// GENERATED by scripts/select-persona.mjs — do not edit. Locales discovered from the i18n folders.",
  ...eng.imports,
  ...per.imports,
  "export const ENGINE_TABLES: Record<string, Record<string, string | string[]>> = {",
  ...eng.map,
  "};",
  "export const PERSONA_TABLES: Record<string, Record<string, string | string[]>> = {",
  ...per.map,
  "};",
].join("\n") + "\n");
console.log(`i18n: engine [${eng.codes.join(", ")}]` + (per.codes.length ? ` + persona [${per.codes.join(", ")}]` : ""));
