/* ================= ENTRY ================= */
// Cloudflare Worker entry point (export default { fetch }) + a «barrel»: re-export of the entire
// internal surface of the modules for unit tests (the harness imports exactly this file).
// The runtime uses only export default; the export * are harmless to the runtime.

// IMPORTANT: register the persona FIRST — before loading flow/commands/config, which on module-load
// merge its commands/config into their maps (COMMANDS/buildCommandRegex/...). The pack does not pull in
// commands.ts transitively, so the order is safe and the composition turns out eager.
// ./persona/active.ts is GENERATED by scripts/select-persona.mjs from the env PERSONA_PACK (path to the pack);
// without it — the neutral ./default. The engine does not know the name of any specific pack.
import "./persona/active";
import { handleTelegramMessage, runDailySummaries } from "./flow";
import { reportError, maybeSyncBotCommands } from "./telegram";
import type { Env, TgUpdate } from "./types";

export default {
  async fetch(request: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
    if (request.method === "POST") {
      // Origin check: if a webhook secret is configured, require Telegram's header to match. Otherwise a
      // forged POST to the worker URL could impersonate ANY user (incl. an admin, since /admin trusts
      // msg.from.username). Optional so an existing deployment isn't locked out until it sets the secret +
      // re-runs setWebhook(secret_token=…); silent 200 on mismatch (no info leak, no retry storm).
      if (env.TELEGRAM_WEBHOOK_SECRET && request.headers.get("X-Telegram-Bot-Api-Secret-Token") !== env.TELEGRAM_WEBHOOK_SECRET) {
        return new Response("ok");
      }
      const update = (await request.json().catch(() => null)) as TgUpdate | null;
      const isEdit = !!(update && update.edited_message);
      const msg = update && (update.message || update.edited_message);
      // Let through only text / photos / stickers (other types are ignored).
      if (!msg || (!msg.text && !msg.photo && !msg.sticker)) return new Response("ok");

      // Protection against re-processing: on a slow response Telegram resends the same update
      // again. Keyed by update_id we set a flag in KV; if it already exists — it's a duplicate, stay silent.
      const updateId = update?.update_id;
      if (updateId !== undefined && env.KV) {
        const dKey = "dedup:" + updateId;
        try {
          if (await env.KV.get(dKey)) return new Response("ok"); // already processed
          // TTL of 5 minutes: Telegram doesn't retry longer than that, and there's no point hoarding flags.
          await env.KV.put(dKey, "1", { expirationTtl: 300 });
        } catch (e: any) {
          console.warn("dedup check failed", { err: e?.message || e });
        }
      }

      // IMPORTANT: process SYNCHRONOUSLY (await), not via ctx.waitUntil.
      // With waitUntil the background task may be aborted before the LLM reply
      // manages to go out to Telegram (the model responded, but sendMessage didn't run).
      // Synchronous processing keeps the worker alive until the end. Telegram waits for a
      // webhook response ~60s — we fit within that as long as the LLM timeout (LLM_TIMEOUT_MS) is smaller.
      // We swallow errors so as to always return 200 (otherwise Telegram will send a duplicate).
      try {
        await handleTelegramMessage(msg, env, isEdit);
      } catch (e: any) {
        await reportError(env, "handleTelegramMessage", e, { critical: true });
      }
      return new Response("ok");
    }
    return new Response("Telegram ↔ OpenRouter worker (TS) is running.");
  },

  // Cron Triggers (wrangler.jsonc triggers.crons, set by the deployment). A thin wrapper:
  // the «08:00 in cfg.timezone» gate and the dispatch itself live inside runDailySummaries (so it's testable).
  // We take the time from event.scheduledTime (not Date.now). We swallow errors so the cron doesn't fail noisily.
  async scheduled(event: ScheduledController, env: Env, _ctx: ExecutionContext): Promise<void> {
    // Refresh the native command menu when the command set changed (guarded by a fingerprint KV flag, so
    // it's effectively once per deploy-that-changes-commands). Best-effort — never blocks the summaries.
    try {
      await maybeSyncBotCommands(env);
    } catch (e: any) {
      await reportError(env, "maybeSyncBotCommands", e);
    }
    try {
      await runDailySummaries(env, event.scheduledTime);
    } catch (e: any) {
      await reportError(env, "runDailySummaries", e, { critical: true });
    }
  },
};

/* ================= TEST SURFACE (barrel) ================= */
// Re-export of all modules in one place. A new unit-testable function will become available
// to the tests automatically — it's enough to `export` it from its own module.
export * from "./constants";
export * from "./i18n";
export * from "./utils";
export * from "./prompts";
export * from "./rag";
export * from "./storage";
export * from "./telegram";
export * from "./llm";
export * from "./config";
export * from "./vision";
export * from "./summary";
export * from "./curation";
export * from "./commands";
export * from "./flow";
export * from "./persona/registry";
